# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4

# Command to install dependencies
install: "make"

# Command to run tests, e.g. python setup.py test
script:
  - make test

